version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8080:80"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend